justeat/ZendeskApiClient

- src/ZendeskApi.Acceptance/App.config
- src/ZendeskApi.Acceptance/TicketCommentSteps.cs
- src/ZendeskApi.Acceptance/TicketSteps.cs
- src/ZendeskApi.Acceptance/Tickets.feature
- src/ZendeskApi.Acceptance/Tickets.feature.cs
- src/ZendeskApi.Acceptance/UserIdentityResourceSteps.cs
- src/ZendeskApi.Contracts/Models/CustomField.cs
- src/ZendeskApi.Contracts/Models/Ticket.cs
- src/ZendeskApi.Contracts/ZendeskApi.Contracts.csproj
Updating the email address used in the tests to make it more unique so it doesn't class with other test data
> Moving all tests to add a first comment instead of a description.

- src/ZendeskApi.Client.Tests/Resources/UserIdentityResourceFixture.cs
- src/ZendeskApi.Client/Resources/UserIdentityResource.cs
> #19: Fix user identity PUT method

- src/ZendeskApi.Contracts/Queries/ZendeskQuery.cs
> #21: URL encode query string values

- src/ZendeskApi.Contracts.Tests/Queries/ZendeskQueryFixture.cs
> Fix failing tests for changes in #22

- README.md
I've noticed a small typo in the Readme
> Update example usage for correct IListResponse when searching for users

- src/ZendeskApi.Client/Http/HttpChannel.cs
Shouldn't default to async under the hood as it can result in unexpected behaviour. Making async a choice of the user.
> Shouldn't default to async under the hood

- src/ZendeskApi.Acceptance/SatisfactionRatingSteps.cs
- src/ZendeskApi.Acceptance/SearchSteps.cs
- src/ZendeskApi.Contracts.Tests/Queries/ZendeskQueryFixture.cs
- src/ZendeskApi.Contracts/Models/Filter.cs
- src/ZendeskApi.Contracts/Models/FilterOperator.cs
- src/ZendeskApi.Contracts/Queries/IZendeskQuery.cs
- src/ZendeskApi.Contracts/Queries/ZendeskQuery.cs
- src/ZendeskApi.Contracts/ZendeskApi.Contracts.csproj
I wanted the ability to search for tickets that had been updated in the last day. So I changed the Query object to accept a third parameter. An enum with values Equals, LessThan, or GreaterThan. That way we can leverage the API a little more with the queries.
Side Note: First pull request ever....Any advice is more than welcome!
> Added ability to change search queries operator. (=, <, >)

- src/ZendeskApi.Contracts/Models/Organization.cs
> Move domain names to non-ignored property of Organisation

- src/ZendeskApi.Acceptance/Organization.feature
- src/ZendeskApi.Acceptance/Organization.feature.cs
- src/ZendeskApi.Acceptance/OrganizationSteps.cs
- src/ZendeskApi.Acceptance/ZendeskApi.Acceptance.csproj
- src/ZendeskApi.Client.Tests/Resources/OrganizationResourceFixture.cs
- src/ZendeskApi.Client/Resources/IOrganizationResource.cs
- src/ZendeskApi.Client/Resources/OrganizationResource.cs
- src/ZendeskApi.Client/Resources/ZendeskResource.cs
https://developer.zendesk.com/rest_api/docs/core/organizations#show-many
-organizations
> Adding support for 'show organisations by external_id'

- src/ZendeskApi.Client.Abstractions/Models/Request.cs
- src/ZendeskApi.Client.Abstractions/Models/Ticket.cs
- src/ZendeskApi.Client.Abstractions/Models/TicketField.cs
- src/ZendeskApi.Client.Abstractions/Models/TicketForm.cs
- src/ZendeskApi.Client.Abstractions/Models/TicketRequester.cs
- src/ZendeskApi.Client.Abstractions/Models/User.cs
Based on https://developer.zendesk.com/rest_api/docs/core/introduction#id-integers
> All int's to long's

- src/ZendeskApi.Client/IZendeskClient.cs
- src/ZendeskApi.Client/Models/UserField.cs
- src/ZendeskApi.Client/Resources/IUserFieldsResource.cs
- src/ZendeskApi.Client/Resources/UserFieldsResource.cs
- src/ZendeskApi.Client/Responses/UserFieldsResponse.cs
- src/ZendeskApi.Client/ZendeskClient.cs
- test/ZendeskApi.Client.Tests/Resources/UserFieldsResourceTests.cs
- test/ZendeskApi.Client.Tests/ResourcesSampleSites/UserFieldsResourceSampleSite.cs
> Added UserFields Resource

- src/ZendeskApi.Client/Requests/OrganizationCreateRequest.cs
- src/ZendeskApi.Client/Resources/OrganizationsResource.cs
- src/ZendeskApi.Client/Responses/OrganizationResponse.cs
- src/ZendeskApi.Client/Responses/OrganizationsResponse.cs
- test/ZendeskApi.Client.Tests/Resources/OrganizationResourceTests.cs
- test/ZendeskApi.Client.Tests/ResourcesSampleSites/OrganizationResourceSampleSite.cs
See: https://developer.zendesk.com/rest_api/docs/core/organizations#create-organization
Added wrapper for the response and request where the organization will be wrapped.
Also added tests for this resource. They're not exhaustive, only covering what I use at the moment.
> Fixed Organization create + fetch

- src/ZendeskApi.Client/Resources/ITicketsResource.cs
- src/ZendeskApi.Client/Resources/TicketsResource.cs
- test/ZendeskApi.Client.Tests/Resources/TicketsResourceTests.cs
- test/ZendeskApi.Client.Tests/ResourcesSampleSites/TicketResourceSampleSite.cs
GetTicket response is an object with a ticket property, rather than the ticket as the object.
> fix shape of GetTicket response

- .gitignore
- src/ZendeskApi.Client/Models/Organization.cs
- src/ZendeskApi.Client/Responses/GroupResponse.cs
- src/ZendeskApi.Client/Responses/OrganizationsResponse.cs
- src/ZendeskApi.Client/Responses/TicketResponse.cs
- src/ZendeskApi.Client/Responses/UserResponse.cs
Organization, GroupResponse, OrganizationResponse, TicketResponse, and userResponse
> Public setters for Entity Classes to assist unit test mocking

- src/ZendeskApi.Client/Extensions/AuthorizationHeaderExtensions.cs
- src/ZendeskApi.Client/Extensions/ServiceCollectionExtensions.cs
- src/ZendeskApi.Client/Options/ZendeskOptions.cs
- src/ZendeskApi.Client/ZendeskApiClient.cs
- test/ZendeskApi.Client.Tests/ZendeskApiClientTests.cs
Added Support to create Zendesk HTTP Client with OAuthToken.
Added/modified relevant ZendeskApiClientTests as well.
> Added Support to create Zendesk HTTP Client with OAuthToken.

- src/ZendeskApi.Client/Models/Attachment.cs
Fixed issue https://github.com/justeat/ZendeskApiClient/issues/121
> The jsonproperty filename should be file_name

- src/ZendeskApi.Client/ZendeskApiClient.cs
Adds c'tor for ZendeskApiClient that allows overriding of what HttpMessageHandler is being used. (This is useful when one wants to decorate made HTTP calls, e.g. for logging or rate limiting.)
> Allow overriding of HttpMessageHandler

- src/ZendeskApi.Client/ZendeskApi.Client.nuspec
- src/ZendeskApi.Contracts/Models/Request.cs
- src/ZendeskApi.Contracts/Models/Ticket.cs
- src/ZendeskApi.Contracts/Models/TicketField.cs
- src/ZendeskApi.Contracts/Models/TicketForm.cs
- src/ZendeskApi.Contracts/Models/TicketRequester.cs
- src/ZendeskApi.Contracts/Models/User.cs
for https://github.com/justeat/ZendeskApiClient/issues/123
> Some fields of int remains in v2 branch

- src/ZendeskApi.Client/Exceptions/ZendeskRequestExceptionBuilder.cs
- src/ZendeskApi.Client/Resources/UsersResource.cs
- test/ZendeskApi.Client.Tests/Resources/UsersResourceTests.cs
- test/ZendeskApi.Client.Tests/ResourcesSampleSites/UsersResourceSampleSite.cs
> Added Create_or_update for user resources

- appveyor.yml
- src/ZendeskApi.Build/ZendeskApi.Commons.props
- src/ZendeskApi.Client/Extensions/HttpClientExtensions.cs
- src/ZendeskApi.Client/Resources/ISearchResource.cs
- src/ZendeskApi.Client/Resources/SearchResource.cs
- src/ZendeskApi.Client/ZendeskApi.Client.csproj
Added the optional parameter of a CancelationToken within the SearchResource which can also be passed into the `GetAsync` extension method.
> Implemented CancelationTokens within the Search Resource

- src/ZendeskApi.Client/Requests/OrganizationUpdateRequest.cs
- src/ZendeskApi.Client/Resources/OrganizationsResource.cs
Fix update organisation as per: https://developer.zendesk.com/rest_api/docs/support/organizations#update-organization
> fix update organisation data must be in an organisation property.

- src/ZendeskApi.Client/Resources/Interfaces/Ticket/IDeletedTicketsResource.cs
- src/ZendeskApi.Client/Resources/Ticket/DeletedTicketsResource.cs
- test/ZendeskApi.Client.Tests/DisposableZendeskApiClient.cs
- test/ZendeskApi.Client.Tests/Resources/DeletedTicketsResourceTests.cs
- test/ZendeskApi.Client.Tests/ResourcesSampleSites/Ticket/DeletedTicketResourceSampleSite.cs
* Fixed responses given from `DeletedTicketResource.PurgeAsync` methods.
* Renamed List methods to `GetAllAsync`
> Fixed Deleted Ticket Resource & Unit Tests.

- src/ZendeskApi.Client/Resources/GroupsResource.cs
- src/ZendeskApi.Client/Resources/Interfaces/IGroupsResource.cs
- src/ZendeskApi.Client/Resources/Interfaces/IJobStatusResource.cs
- src/ZendeskApi.Client/Resources/Interfaces/Organization/IOrganizationMembershipsResource.cs
- src/ZendeskApi.Client/Resources/Interfaces/Ticket/ITicketCommentsResource.cs
- src/ZendeskApi.Client/Resources/Interfaces/Ticket/ITicketsResource.cs
- src/ZendeskApi.Client/Resources/Interfaces/User/IDeletedUsersResource.cs
- src/ZendeskApi.Client/Resources/Interfaces/User/IUsersResource.cs
- src/ZendeskApi.Client/Resources/JobStatusResource.cs
- src/ZendeskApi.Client/Resources/Organization/OrganizationMembershipsResource.cs
- src/ZendeskApi.Client/Resources/Ticket/TicketCommentsResource.cs
- src/ZendeskApi.Client/Resources/Ticket/TicketsResource.cs
- src/ZendeskApi.Client/Resources/User/DeletedUsersResource.cs
- src/ZendeskApi.Client/Resources/User/UserIdentitiesResource.cs
- src/ZendeskApi.Client/Resources/User/UsersResource.cs
- test/ZendeskApi.Client.Tests/Resources/DeletedUsersResourceTests.cs
- test/ZendeskApi.Client.Tests/Resources/GroupsResourceTests.cs
- test/ZendeskApi.Client.Tests/Resources/JobStatusResourceTests.cs
- test/ZendeskApi.Client.Tests/Resources/OrganizationMembershipsResourceTests.cs
- test/ZendeskApi.Client.Tests/Resources/TicketCommentsResourceTests.cs
- test/ZendeskApi.Client.Tests/Resources/TicketsResourceTests.cs
- test/ZendeskApi.Client.Tests/Resources/UserIdentitiesResourceTests.cs
- test/ZendeskApi.Client.Tests/Resources/UsersResourceTests.cs
Thought I'd go through and make the List vs GetAll battle consistent as GetAll won when discussed. The other thing I've noticed when going through this is we have a few inconsistencies when it comes to: 
- GetForUser / GetByUserId 
- GetAll / GetAllByUserId / GetAllForUser 
This could be a good time to tidy these up too in order to make the interfaces consistent.
> List to getall consistency

- ZendeskApiClient.sln.DotSettings
- appveyor.yml
- src/ZendeskApi.Build/ZendeskApi.Commons.props
- src/ZendeskApi.Client/IZendeskApiClient.cs
- src/ZendeskApi.Client/IZendeskClient.cs
- src/ZendeskApi.Client/Models/Component.cs
- src/ZendeskApi.Client/Models/ComponentImpact.cs
- src/ZendeskApi.Client/Models/ComponentStatus.cs
- src/ZendeskApi.Client/Models/Incident.cs
- src/ZendeskApi.Client/Models/IncidentUpdate.cs
- src/ZendeskApi.Client/Models/ServiceStatus.cs
- src/ZendeskApi.Client/Models/SubComponent.cs
- src/ZendeskApi.Client/Resources/Interfaces/IServiceStatusResource.cs
- src/ZendeskApi.Client/Resources/ServiceStatusResource.cs
- src/ZendeskApi.Client/ZendeskApiClient.cs
- src/ZendeskApi.Client/ZendeskApiClientFactory.cs
- src/ZendeskApi.Client/ZendeskClient.cs
- test/ZendeskApi.Client.IntegrationTests/Resources/ServiceStatusResourceTests.cs
- test/ZendeskApi.Client.Tests/DisposableZendeskApiClient.cs
https://github.com/justeat/ZendeskApiClient/projects/1#card-24161743
> add status api resource

- appveyor.yml
- src/ZendeskApi.Client/Resources/Interfaces/Organization/IOrganizationFieldsResource.cs
- src/ZendeskApi.Client/Resources/Organization/OrganizationFieldsResource.cs
- src/ZendeskApi.Client/ZendeskApi.Client.csproj
- src/ZendeskApi.Client/ZendeskClient.cs
This was missed in previous PR(#218)
> Added OrganizationFields Resource into Zendesk Client

- appveyor.yml
- src/ZendeskApi.Build/ZendeskApi.Commons.props
- src/ZendeskApi.Client/Requests/Ticket/TicketTagListsUpdateRequest.cs
- src/ZendeskApi.Client/Requests/Ticket/TicketUpdateRequest.cs
- src/ZendeskApi.Client/Resources/Interfaces/Ticket/ITicketsResource.cs
- src/ZendeskApi.Client/Resources/Ticket/TicketsResource.cs
- test/ZendeskApi.Client.Tests/Resources/TicketsResourceTests.cs
- test/ZendeskApi.Client.Tests/ResourcesSampleSites/Ticket/TicketResourceSampleSite.cs
Added https://developer.zendesk.com/rest_api/docs/support/tickets#updating-tag-lists support
> Add updating tag lists endpoint
