src/ZendeskApi.Acceptance/Tickets.feature
src/ZendeskApi.Acceptance/Tickets.feature.cs
src/ZendeskApi.Acceptance/ZendeskApi.Acceptance.csproj

Fixing .net 4 acceptance test issues - app settings is required for all framework versions as it may contain connection strings.
Also updating the tickets test. The acceptance tests use just eat's sandbox and someone has set the custom field used to a check box so the value used in the test has to be true/false.

Fixing .net 4 acceptance test issues

---

src/ZendeskApi.Contracts/Models/User.cs

Add user fields to User model to support Zendesk custom fields. See `user_fields` under https://developer.zendesk.com/rest_api/docs/core/users.

Add user fields to User model

---

src/ZendeskApi.Contracts/Models/Request.cs

Custom fields cannot be added to Request objects since the `CustomFields` member is both private and uninitialised.  Added a constructor to Request.cs to initialise the list.

Initialise CustomFields list in Request class

---

src/ZendeskApi.Contracts/Models/TicketStatus.cs

Add Hold Ticket Status to Models. Allows ZenDesk accounts with Hold
ticket status enabled to use the API.

Add Hold Ticket Status

---

src/ZendeskApi.Contracts/Models/Request.cs
src/ZendeskApi.Contracts/Models/Ticket.cs

Great work on the Zendesk API client! I appreciate the work you've put into it!
I saw the 2 issues submitted by @bmnielsen about tags and custom fields. I'm experiencing the same issues, so I took a quick try at a fix. The change is simple and seems to work well. 
Applying the [DataMember] attribute for tags was all that was required to set tags. And removing the private keyword from the setter on CustomFields allowed me to specify tags at ticket creation. Was there a specific reason you were using a private set? 
Let me know what you think.

support for setting tags and custom fields

---

src/ZendeskApi.Contracts/Models/Ticket.cs

I was using this API and came across a few issues that I was able to fix internally. I am not sure if ExternalId purposely had [IgnoreDataMember] set but I was unable to access it when writing or reading a ticket, so I added the DataMember name. I also needed to access priority, so I added the name there as well.

Added DataMember names for priority and external_id

---

src/ZendeskApi.Contracts/Models/Ticket.cs
src/ZendeskApi.Contracts/Models/TicketRequester.cs
src/ZendeskApi.Contracts/ZendeskApi.Contracts.csproj

It's weird that they don't define this property within the Ticket object itself, only partially noted in docs here.
https://developer.zendesk.com/rest_api/docs/core/tickets#creating-a-ticket-with-a-new-requester
Useful for creating a ticket with new (or old) requester.

Additional requester property for Ticket API

---

src/ZendeskApi.Acceptance/TicketSteps.cs
src/ZendeskApi.Contracts/Models/CustomField.cs

Fixes #47. Presents custom field IDs as `long`.

Custom fields are long, not int

---

src/ZendeskApi.Contracts/Models/Organization.cs
src/ZendeskApi.Contracts/Models/Ticket.cs

Hi,
this is my first pull request, i'm newbie in GItHub and I hope that i've done things correctly.
I found this problem that causes newtonsoft to throw a serialization exception in case External_Id is setted to a non long value (a string).
As Zendesk's api says [zendesk] (https://developer.zendesk.com/rest_api/docs/core/tickets#content) external id is a string not a long. 
I've just modified it, the types of the properties.

External_Id field, incorrect type long? converted to string

---

src/ZendeskApi.Client/Resources/IUsersResource.cs
src/ZendeskApi.Client/Resources/UsersResource.cs
src/ZendeskApi.Client/Responses/IncrementalUsersResponse.cs
test/ZendeskApi.Client.Tests/Resources/UsersResourceTests.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/UsersResourceSampleSite.cs
test/ZendeskApi.Client.Tests/Responses/IncrementalUsersResponseTests.cs

See: https://developer.zendesk.com/rest_api/docs/core/incremental_export#incremental-user-export
Added new method to the Users resource, as well as tests for resource and deserializing.
Note: pagination is a bit different for incremental exports, so the PaginationResponse will not have a valid pager. That's why it also has a HasMoreResults property, to let the client check for more results using the EndTime property for the next request. Ex:
```csharp
var startTime = DateTime.UtcNow;
IncrementalUsersResponse<UserResponse> response;
do
{
response = await _client.Users.GetIncrementalExport(startTime);
startTime = response.EndTime;
Console.WriteLine($"Found {response.Count} changed users!");
foreach (var user in response.Users)
{
Console.WriteLine($"\t-> User \"{user.Name}\", email: …
```

Added Incremental Export to Users resource

---

src/ZendeskApi.Client/Extensions/HttpRequestExtensions.cs
src/ZendeskApi.Client/Models/Attachment.cs
src/ZendeskApi.Client/Resources/AttachmentsResource.cs
src/ZendeskApi.Client/Resources/IAttachmentsResource.cs
src/ZendeskApi.Client/Responses/UploadResponse.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/AttachmentsResourceSampleSite.cs
test/ZendeskApi.Client.Tests/Responses/UploadResponseTests.cs

Re-submit of #94 
Fixes #93
Changed the binary upload to not upload with multipart boundaries, now just uploading pure binary content
Fixed tests accordingly
Added UploadResponse as a wrapper for the Upload object, and also added a deserializing test for this, with a real-life example response (I had an issue where the Upload object would not deserialize properly)

Fixed attachment uploading

---

src/ZendeskApi.Client/Resources/UsersResource.cs
src/ZendeskApi.Client/Responses/SingleUserResponse.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/UsersResourceSampleSite.cs

See: https://developer.zendesk.com/rest_api/docs/core/users#create-user 
The endpoints for getting a single user, creating a user and updating a single user alle returns the user wrapped in a { user: { ... } } object. That's why I added the "SingleUserResponse" object.
I would preferably refactor the "UserResponse" object, but it's used in several other responses, so I didn't want to break anything. I feel like the resource should ideally just return a general "User" object, in the same vein as the organization resource does.

Fixed user create, fetch and update

---

src/ZendeskApi.Client/Models/CustomFields.cs
src/ZendeskApi.Client/Requests/TicketCreateRequest.cs
src/ZendeskApi.Client/Responses/TicketResponse.cs
test/ZendeskApi.Client.Tests/Resources/TicketCommentsResourceTests.cs

1. `CustomFields` has dictionary type characteristics, so allow initialisation from one
2. Don't use the `description` key when creating a ticket, as ZD documentation suggests
3. Ticket `id` field was not deserialising as casing was wrong on `TicketRespons`.  Added `JsonProperty`

Minor improvements

---

src/ZendeskApi.Client/Resources/ITicketsResource.cs
src/ZendeskApi.Client/Resources/TicketsResource.cs
src/ZendeskApi.Client/Responses/TicketResponseContainer.cs
test/ZendeskApi.Client.Tests/Resources/TicketCommentsResourceTests.cs
test/ZendeskApi.Client.Tests/Resources/TicketsResourceTests.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/TicketResourceSampleSite.cs

As documented at https://developer.zendesk.com/rest_api/docs/core/tickets#create-ticket, the response to a create or update ticket request is not the ticket directly, but instead an object with a ticket property.

Fix ticket create and update responses

---

src/ZendeskApi.Client/Converters/CustomFieldConverter.cs
src/ZendeskApi.Client/Models/CustomField.cs
src/ZendeskApi.Client/Models/CustomFields.cs
src/ZendeskApi.Client/Models/ICustomFields.cs
src/ZendeskApi.Client/Models/IReadOnlyCustomFields.cs
test/ZendeskApi.Client.Tests/Converters/CustomFieldConverterTests.cs
test/ZendeskApi.Client.Tests/Converters/testTicket.json
test/ZendeskApi.Client.Tests/ZendeskApi.Client.Tests.csproj

- new property added to CustomField to account for custom fields where the value is an array instead of a primitive
- custom serializer/deserializer for CustomField and tests for the serializer/deserializer
- adjusted the contract (additive change) of CustomFields to account for the changes to CustomField

CustomField allows value arrays

---

src/ZendeskApi.Client/Converters/CustomFieldConverter.cs
test/ZendeskApi.Client.Tests/Converters/CustomFieldConverterTests.cs
test/ZendeskApi.Client.Tests/Converters/testTicketNull.json
test/ZendeskApi.Client.Tests/ZendeskApi.Client.Tests.csproj

Fixes backwards compatibility issue where `null`-valued custom fields were rendered as `{ 1234: [ null ] }` i.e. array valued.

Adds handling of `null` values for custom fields to the CustomFieldConverter

---

src/ZendeskApi.Client/IZendeskClient.cs
src/ZendeskApi.Client/Resources/DeletedUsersResource.cs
src/ZendeskApi.Client/Resources/IDeletedUsersResource.cs
src/ZendeskApi.Client/Resources/UsersResource.cs
src/ZendeskApi.Client/ZendeskClient.cs
test/ZendeskApi.Client.Tests/Resources/DeletedUsersResourceTests.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/DeletedUsersResourceSampleSite.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/UsersResourceSampleSite.cs

The `DELETE /users/{id}` endpoint returns `OK`, but the client expects a `NoContent` response, so it currently fails.
Also, I added the `/deleted_users` endpoint which allow to permanently delete users. https://developer.zendesk.com/rest_api/docs/core/users#list-deleted-users

Fixed Delete Users response, added Deleted Users endpoint

---

appveyor.yml
src/ZendeskApi.Client/Converters/JobStatusResultConverter.cs
src/ZendeskApi.Client/IZendeskClient.cs
src/ZendeskApi.Client/Models/JobStatus.cs
src/ZendeskApi.Client/Resources/IJobStatusResource.cs
src/ZendeskApi.Client/Resources/JobStatusResource.cs
src/ZendeskApi.Client/Responses/JobStatusListResponse.cs
src/ZendeskApi.Client/Responses/SingleJobStatusResponse.cs
src/ZendeskApi.Client/ZendeskClient.cs
test/ZendeskApi.Client.Tests/Converters/JobStatusResultConverterTests.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/JobStatusResourceSampleSite.cs

* New `JobStatus` Resource has been created
* `JobStatusResultConverter` had to be created to workaround an issue in the Zendesk 
* Occasionally the **results** key within a job_status would be an Object, instead of an Array (as specified in the API Documentation)

Created JobStatus Resource

---

src/ZendeskApi.Client/ZendeskApi.Client.csproj

Seems as if this version number is also used within Appveyor when creating the NuGet package. Caused an issue in the previous commit in which the minor wasn't correctly updated.

Upped Version Minor in csproj

---

appveyor.yml
src/ZendeskApi.Client/Resources/TicketsResource.cs
src/ZendeskApi.Client/ZendeskApi.Client.csproj

* Fixed expected response code within `TicketResource`'s `CreateAsync` for bulk ticket creation.
* API Returns a 200 OK for bulk creations.
* Fixed HelpDoc Link throughout tickets resource.
* Fixed return object of `TicketResource`'s `CreateAsync` for bulk ticket creation.
* Was parsing the response incorrectly, and creating an empty `JobStatus` object.
* Increased patch version number.

Fixed expected response code when bulk creating tickets

---

appveyor.yml
src/ZendeskApi.Client/Requests/TicketUpdateRequest.cs
src/ZendeskApi.Client/ZendeskApi.Client.csproj

* Changed `TicketUpdateRequest.ExternalId` type to String - as per Zendesk documentation (Resolves #169)
* Increased version patch number (As we're still in alpha).

Resolve #169 - Changed ExternalId field type to string

---

src/ZendeskApi.Client/Requests/TicketFieldCreateRequest.cs
src/ZendeskApi.Client/Requests/TicketFieldCreateUpdateRequest.cs
src/ZendeskApi.Client/Resources/TicketFieldsResource.cs
test/ZendeskApi.Client.Tests/ResourcesSampleSites/TicketFieldsResourceSampleSite.cs

* Fixes the [`TicketFieldsResource.CreateAsync`](https://github.com/justeat/ZendeskApiClient/pull/171/files#diff-5a752b961565f3560c3f259a37541ef4R62) method (resolves #144)
* Fixes the [`TicketFieldsResource.UpdateAsync`](https://github.com/justeat/ZendeskApiClient/pull/171/files#diff-5a752b961565f3560c3f259a37541ef4R83) method.
* Implemented a new [`TicketFieldCreateUpdateRequest`](https://github.com/justeat/ZendeskApiClient/pull/171/files#diff-8c817f3c015789957b7d42f7c4ef37abR10) which is used when sending off TicketFields Create/Update requests.

Fixes Request Problems within TicketFields Resource

---

appveyor.yml

recently upgraded image from VS 2015 -> VS 2019
`dotnet pack` on VS 2015 image:
```
dotnet pack .\src\ZendeskApi.Client\ZendeskApi.Client.csproj -o ../../output --no-build
Successfully created package 'C:\projects\zendeskapiclient\output\ZendeskApi.Client.4.0.1-alpha-701.nupkg'.
```
`dotnet pack` on VS 2019 image:
```
dotnet pack .\src\ZendeskApi.Client\ZendeskApi.Client.csproj -o ../../output --no-build
Successfully created package 'C:\output\ZendeskApi.Client.5.0.0-alpha-732.nupkg'
```
You can see from above that the `\projects\zendeskapiclient\` is missing and I think the new version of MS Build is using a different location to execute the commands
PR fixes this. Sample output from this PR:
```
dotnet pack .\src\ZendeskApi.Client\ZendeskApi.Client.csproj -o ./output --no-build …
```

Ensure artifact is generated during "dotnet pack" command

---

README.md
src/ZendeskApi.Client/ZendeskApi.Client.csproj
test/ZendeskApi.Client.IntegrationTests/ZendeskApi.Client.IntegrationTests.csproj
test/ZendeskApi.Client.Tests/ZendeskApi.Client.Tests.csproj

This PR includes:
* upgrading target framework to dotnet6 (pain-free experience)
* adding release notes
* [aside] adding status badge for the `ci` workflow

Upgrade target framework to dotnet6

---

src/ZendeskApi.Build/ZendeskApi.Commons.props
src/ZendeskApi.Client/ZendeskApiClient.cs
src/ZendeskApi.Client/ZendeskApiClientFactory.cs

Sets a default user agent. 
We can now see it in our logs the requests are coming from this SDK . 
@mikerogers123 are you happy with this user agent string?

[RED-2026] Set a default user agent so Zendesk can identify the requests
